#!/usr/bin/env python

import sys

from ni_vision_gui.ni_vision_gui import MyPlugin
from rqt_gui.main import Main

plugin = 'ni_vision_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
